spring:
  application:
    name: custom-plguin
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://localhost:3306/ATest?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  #   username: admin
  #   password: 123456
  # jpa:
  #     hibernate:
  #       ddl-auto: update
  #       # naming:
  #       #   physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #     show-sql: true
  #     properties:
  #       hibernate:
  #         globally_quoted_identifiers: true
  #         dialect: org.hibernate.dialect.MySQL8Dialect

# springdoc-openapi项目配置
# springdoc:
#   swagger-ui:
#     path: /swagger-ui.html
#     tags-sorter: alpha
#     operations-sorter: alpha
#   api-docs:
#     path: /v3/api-docs
#   group-configs:
#     - group: 'default'
#       paths-to-match: '/**'
#       packages-to-scan: com.example.custom_plugin.service
# # knife4j的增强配置，不需要增强可以不配
# knife4j:
#   enable: true
#   setting:
#     language: zh_cn